<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\src\DotnetJobKit\DotnetJobKit.csproj" />
    <ProjectReference Include="..\..\src\DotnetJobKit.Sqlite\DotnetJobKit.Sqlite.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
